name: trackstar_web
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  animate_do: ^3.1.2
  cached_network_image: ^3.3.1
  dio: ^5.3.3
  file_picker: ^6.0.0
  flutter:
    sdk: flutter
  flutter_inappwebview: ^5.8.0
  flutter_svg: ^2.0.7
  go_router: ^11.1.2
  google_fonts: ^6.1.0
  image: ^4.1.7
  image_picker: ^1.0.4
  image_picker_for_web: ^3.0.1
  page_transition: ^2.1.0
  provider: ^6.0.5
  skeletonizer: ^0.8.0
  supabase: ^2.0.8
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/img/
    - assets/svg/
  uses-material-design: true
