const String baseUrl = 'https://tcssnobcmvdajohazudr.supabase.co';
const String apikey =
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRjc3Nub2JjbXZkYWpvaGF6dWRyIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTY5Njk2Njk2NywiZXhwIjoyMDEyNTQyOTY3fQ.XOQjAbsdBmduG_j_IXmZ7pgevbC8Z3XCPF4Xv4_pisg';
