const String baseUrl = 'https://dingeltkwmnfigloarcw.supabase.co';
const String apikey =
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRpbmdlbHRrd21uZmlnbG9hcmN3Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTY5Njg2NDYwOSwiZXhwIjoyMDEyNDQwNjA5fQ.klRm2uY89YV93AaaybEXe5hN6OwLKhcRBMA_MQTx3kw';
