const String baseUrl = 'https://ewjpyvftqnxgmtvvehty.supabase.co';
const String apikey =
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV3anB5dmZ0cW54Z210dnZlaHR5Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTY5ODE5ODY4OCwiZXhwIjoyMDEzNzc0Njg4fQ.NzGLxrCdoUcR8ABXDCBasPkXxNtWah8Q4OKYUDI0A7Q';
