const String baseUrl = 'https://brgnejhxzdymifxsicgn.supabase.co';
const String apikey =
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJyZ25lamh4emR5bWlmeHNpY2duIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTY5ODI2NTY2NCwiZXhwIjoyMDEzODQxNjY0fQ.6QPCg5GdVySjl_5K7URL8I4sSSCKBfs5ZCUEOvMhTIw';
